[package]
name = "aud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev.package."hack"]
opt-level = 2

[dependencies]
hack.path = "./hack"

cpal = "0.14.1"

[workspace]
members = ["hack"]
